version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Bootstrap Lerna
          command: yarn setup
      - run:
          name: Compile TypeScript
          command: yarn build
      - run:
          name: Test Coverage
          command: yarn test:coverage
      - store_test_results:
          path: /coverage
