version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Compile TypeScript
          command: yarn build
      - run:
          name: Run test suite
          command: yarn test:coverage --ci --runInBand
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
